
  [35mScenario[0m: Just a scenario that opens a web page
[90m    Given I start a webserver at directory "data/www" and save the port to the variable "PORT"
[0m[1A    [32mGiven[0m I start a webserver at directory "data/www" and save the port to the variable "PORT"[33m     # started at 2023-09-11T10:38:27.776 took 0.206s[0m
[90m      And I open a browser at the url "http://{HOST_ADDRESS}:{PORT}/buttons.html"
[0m2023-09-11 10:38:27,983 DEBUG opening browser chrome
2023-09-11 10:38:28,384 DEBUG webdriver.Chrome init
2023-09-11 10:38:29,919 DEBUG executing page check "wait for document.readyState"
2023-09-11 10:38:29,923 DEBUG executed page check "wait for document.readyState" in 0.004s
2023-09-11 10:38:29,923 DEBUG executing page check "broken image checker"
2023-09-11 10:38:29,928 DEBUG executed page check "broken image checker" in 0.005s
2023-09-11 10:38:29,929 DEBUG navigating to url #http://10.0.0.55:56368/buttons.html
2023-09-11 10:38:30,034 DEBUG executing page check "wait for document.readyState"
2023-09-11 10:38:30,038 DEBUG executed page check "wait for document.readyState" in 0.004s
2023-09-11 10:38:30,039 DEBUG executing page check "broken image checker"
2023-09-11 10:38:30,042 DEBUG executed page check "broken image checker" in 0.003s
[1A    [32m  And[0m I open a browser at the url "http://{HOST_ADDRESS}:{PORT}/buttons.html"[33m                  # started at 2023-09-11T10:38:27.983 took 2.100s[0m
[34m      # HOST_ADDRESS="10.0.0.55" PORT="56368"
[0m[90m      And I should see the text "inexistent"
[0m2023-09-11 10:38:30,450 DEBUG Retrying cucu.utils.retry.<locals>.new_decorator in 0.25 seconds as it raised RuntimeError: unable to find the text "inexistent".
2023-09-11 10:38:30,763 DEBUG Retrying cucu.utils.retry.<locals>.new_decorator in 0.25 seconds as it raised RuntimeError: unable to find the text "inexistent".
2023-09-11 10:38:31,075 DEBUG Retrying cucu.utils.retry.<locals>.new_decorator in 0.25 seconds as it raised RuntimeError: unable to find the text "inexistent".
2023-09-11 10:38:31,394 DEBUG Retrying cucu.utils.retry.<locals>.new_decorator in 0.25 seconds as it raised RuntimeError: unable to find the text "inexistent".
2023-09-11 10:38:31,705 DEBUG Retrying cucu.utils.retry.<locals>.new_decorator in 0.25 seconds as it raised RuntimeError: unable to find the text "inexistent".
2023-09-11 10:38:32,011 DEBUG Retrying cucu.utils.retry.<locals>.new_decorator in 0.25 seconds as it raised RuntimeError: unable to find the text "inexistent".
2023-09-11 10:38:32,328 DEBUG Retrying cucu.utils.retry.<locals>.new_decorator in 0.25 seconds as it raised RuntimeError: unable to find the text "inexistent".
[1A[31m      And I should see the text "inexistent"[0m[33m                                                       # started at 2023-09-11T10:38:30.372 took 2.281s[0m
Traceback (most recent call last):
  File "/Users/xindong/Library/Caches/pypoetry/virtualenvs/cucu-M6jSuFdm-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/xindong/Work/cucu/src/cucu/utils.py", line 126, in new_decorator
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xindong/Work/cucu/src/cucu/helpers.py", line 121, in base_should_see_the
    raise RuntimeError(f'unable to find the {prefix}{thing} "{name}"')
RuntimeError: unable to find the text "inexistent"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xindong/Library/Caches/pypoetry/virtualenvs/cucu-M6jSuFdm-py3.11/lib/python3.11/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/Users/xindong/Library/Caches/pypoetry/virtualenvs/cucu-M6jSuFdm-py3.11/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "/Users/xindong/Work/cucu/src/cucu/steps/text_steps.py", line 30, in <module>
    helpers.define_should_see_thing_with_name_steps("text", find_text)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xindong/Work/cucu/src/cucu/behave_tweaks.py", line 78, in inner_step_func
    func(*args, **kwargs)
  File "/Users/xindong/Work/cucu/src/cucu/helpers.py", line 62, in wrapper
    func(*args, **kwargs)
  File "/Users/xindong/Work/cucu/src/cucu/helpers.py", line 130, in should_see_the
    retry(
  File "/Users/xindong/Library/Caches/pypoetry/virtualenvs/cucu-M6jSuFdm-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/xindong/Library/Caches/pypoetry/virtualenvs/cucu-M6jSuFdm-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xindong/Library/Caches/pypoetry/virtualenvs/cucu-M6jSuFdm-py3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x10bedf490 state=finished raised RuntimeError>]

2023-09-11 10:38:32,947 DEBUG Saving MHT webpage snapshot: browser_snapshot.mht
2023-09-11 10:38:33,006 DEBUG quitting browser between sessions


Failing scenarios:
  data/features/feature_with_failing_scenario_with_web.feature:4  Just a scenario that opens a web page

0 features passed, 1 failed, 0 skipped
0 scenarios passed, 1 failed, 0 skipped
2 steps passed, 1 failed, 0 skipped, 0 undefined
Took 0m4.586s
Error: test run failed, see above for details
